services:
  oracledb:
    image: oracle/database:19.3.0-ee
    container_name: oracledb
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=672005
    volumes:
      - oracle_data:/opt/oracle/oradata
    restart: unless-stopped

volumes:
  oracle_data:
    external: true
