version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - ./images:/var/www/html/images
      - ./php:/var/www/html/php
      - ./edit.php:/var/www/html/edit.php
      - ./select.php:/var/www/html/select.php
      - ./add.php:/var/www/html/add.php
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  db_data:
